### PR TITLE
Fix u1db reference on requirements 

### PR DESCRIPTION
**Pull request by giovaneliberato**
The packages for u1db and dirspec were removed from pypi. Now we need to download it directly from canonical's launchpad.
Also, updates pixelated repositories references.

### CODE REVIEW

**Comment by shyba** [comment]
@kalikaneko I can confirm Soledad is currently broken under usual install procedure (without those changes to requirements file). Installing dirspec and u1db from url solved this on my environment.
@bwagnerr @giovaneliberato Could you please fix your commits following the [commit style guide](https://github.com/leapcode/soledad/blob/develop/docs/leap-commit-template.README) ?

**Comment by giovaneliberato** [comment]
@shyba sure, could you help me? :D

**Comment by giovaneliberato** [comment]
Commit messages fixed @shyba @kalikaneko

**Comment by kalikaneko** [comment]
u1db team says that they're going to fix the situation with dirspec, but it seems to be taking longer than expected :(
so I think I'll just merge this one for now. (I guess the 93dc55e commit is redundant with the other open PR)

**Comment by kalikaneko** [comment]
u1db team says that they're going to fix the situation with dirspec, but it seems to be taking longer than expected :(
so I think I'll just merge this one for now. (I guess the 93dc55e commit is redundant with the other open PR)

**Comment by bwagnerr** [comment]
Hey @kalikaneko , we are trying to tidy things up and will be removing some of these commits, can you please close this PR?

**Pull request closed without merging**
