### PR TITLE
bug AttributeError: 'module' object has no attribute 'EncryptionMethods'

### PR DESCRIPTION
**Pull request by parmegv**
It seems python complains about a submodule if used inside a subclass.

- Resolves: #7092

### CODE REVIEW

**Comment by parmegv** [comment]
Updated, method=None by default and if it's not specified, then AES_256_CTR is used.

**Comment by ivanalejandro0** [comment]
if you're getting `AttributeError: 'module' object has no attribute 'EncryptionMethods' ` for the line  `crypto.EncryptionMethods.AES_256_CTR` you won't fix it by moving it from the parameters to a line inside the function, the problem is somewhere else. Maybe you don't see the problem anymore because the parameter is not `None` and the troublesome line does not get executed.

Is there any bug on redmine related with this? or maybe any log of this problem to see what's happenning.

**Comment by andrejb** [comment]
@parmegv has opened a bug in redmine with some logs: https://leap.se/code/issues/7092

I also don't quite get what might be wrong there, and why the proposed solution would fix it. I'll comment something that comes to my mind in the issue.

**Comment by parmegv** [comment]
You were right, the code didn't have the problem. I recreated the virtualenv and this error is gone.

**Pull request closed without merging**
