### PR TITLE
[refactor] refactor http_target and part of couch.py

### PR DESCRIPTION
**Pull request by shyba**
I took some time to understand the upload and meanwhile refactored some of Soledad code.
Also, fixed a small bug while checking for BadRequest.
@drebs already commented on them. I am fixing and will comment here when done.

### CODE REVIEW

**Comment by shyba** [comment]
@drebs -- check :D 
Ready for review.

**Comment by kalikaneko** [comment]
finished commenting

**Comment by kalikaneko** [comment]
assigning drebs back, yesterday I assigned to myself because I thought this was ready to merge.
There are a couple of unanswered comments:
https://github.com/pixelated/soledad/commit/5ca9b552e1eaa134092202e0b46e90bb5c5fe49b#commitcomment-12789558
https://github.com/pixelated/soledad/commit/4c018ecbbeb5f60268fb3572cfed30188b3597ae

**Comment by shyba** [comment]
https://github.com/pixelated/soledad/commit/4c018ecbbeb5f60268fb3572cfed30188b3597ae solved on client side by https://github.com/pixelated/soledad/commit/adc02db8afe1af8e7831b68580bf04550bade49f

https://github.com/pixelated/soledad/commit/5ca9b552e1eaa134092202e0b46e90bb5c5fe49b#commitcomment-12789558 doc revision in this case (no doc on couch) is sent by client, see https://github.com/leapcode/soledad/blob/develop/server/src/leap/soledad/server/sync.py#L393
In that case, I think maybe __init__.py (server handler) should raise BadRequest if no rev is given on upload, since the client should always know what revision he is uploading. Thoughts?

**Comment by ivanalejandro0** [comment]
Don't forget to add the corresponding changes files.
Example: https://github.com/leapcode/soledad/pull/256/files#diff-a673b6b1af2225c30fab807918b0d7c0R1
Each of those files is used during tag/release to build the changelog file (see https://github.com/leapcode/soledad/blob/develop/CHANGELOG)

**Comment by shyba** [comment]
Just added changes file. Thanks for remembering @ivanalejandro0

**Comment by ivanalejandro0** [comment]
> Just added changes file. Thanks for remembering @ivanalejandro0

cool, thanks!

**Pull request merged**
