### PR TITLE
[pkg] bump compat versions for leap deps

### PR DESCRIPTION
**Pull request by andrejb**

### CODE REVIEW

**Comment by andrejb** [comment]
This should also take care of https://github.com/leapcode/soledad/pull/187, thanks @hnaparst for that!

**Comment by ivanalejandro0** [comment]
We should test if we no longer have the problem which lead us to ping `PyOpenSSL<0.14`.
see https://github.com/leapcode/soledad/commit/9769301256f994061111e9a18beae90160cc809f  and https://leap.se/code/issues/5368

**Comment by ivanalejandro0** [comment]
We already have documented `libffi-dev` on https://leap.se/en/docs/client/dev-environment#install-dependencies so I think this change won't be a problem.

**Comment by kalikaneko** [comment]
what's the status of this? there was another pr covering part of this, wasn't it? but the pinning should be landed on develop

**Comment by kalikaneko** [comment]
...and it's merged. thanks @andrejb

**Pull request merged**
