### PR TITLE
Refactor sync lock and threadpool

### PR DESCRIPTION
**Pull request by andrejb**

### CODE REVIEW

**Comment by kalikaneko** [comment]
Looks ok to me.
I think the only lingering question I have still is: what happens if many syncs are queued up in the deferredLock? is it possible to cancel all of them?

**Comment by kalikaneko** [comment]
sync seems to hang on this branch: https://paste.antagonismo.org/#uwZVcT4A1sfT-Mt6NIwvSQ

**Comment by andrejb** [comment]
The hang is fixed with the latest commit ("wait for db init on sync decrypter pool").

**Comment by andrejb** [comment]
Just to document the answer to kali's question, the cancelling of syncs is the next issue i'llbe working on.

**Comment by kalikaneko** [comment]
with latest commit, I'm still experiencing a hang, same place.

**Pull request merged**
