### PR TITLE
Feat/real batching for upload

### PR DESCRIPTION
**Pull request by shyba**
WIP
Depends on https://github.com/leapcode/soledad/pull/292

This PR adds real upload batching on soledad server.
All documents should be inserted in a single request.
It's done and all tests passes, but I am putting WIP because I am unsure if couchdb 1.6+ will be officially supported here and if current code will run on bigcouch. If not, we can add a toggle to enable it by conf file.

### CODE REVIEW

**Comment by kalikaneko** [comment]
this PR should be rebased against develop when #292 is merged

**Comment by kalikaneko** [comment]
re. the "in a better way" above, I was thinking either reading a config file, or passing the parameter in the constructor.

**Comment by kalikaneko** [comment]
I'm a bit lost... what's the status of this?
We were waiting until it can automatically check whether the server has batching capability, right?

**Comment by shyba** [comment]
@kalikaneko 
As we talked, this last commit disables all batching variables, making this new feature dead by default.
We are deferring the granular configuration and should enabled by default later, after testing on our (LEAP/Pixelated) environments. Last commit contains instructions on how to enable it for testing.
@andrejb ping. :D We need to test this heavily.

**Pull request merged**
